

services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: sahil26102002/helpdesk-client:latest
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: sahil26102002/helpdesk-client:latest
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/helpdesk
      - JWT_SECRET=your-super-secret-key-that-is-long
      - STUB_MODE=true
      - AUTO_CLOSE_ENABLED=true
      - CONFIDENCE_THRESHOLD=0.75

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: